//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp.Generated
{
    public struct PlayerCommandSerializer : ICommandDataSerializer<PlayerCommand>
    {
        public void Serialize(ref DataStreamWriter writer, in PlayerCommand data)
        {
            writer.WriteUInt(data.Keys);
        }

        public void Deserialize(ref DataStreamReader reader, ref PlayerCommand data)
        {
            data.Keys = (byte) reader.ReadUInt();
        }

        public void Serialize(ref DataStreamWriter writer, in PlayerCommand data, in PlayerCommand baseline, NetworkCompressionModel compressionModel)
        {
            writer.WritePackedUIntDelta(data.Keys, baseline.Keys, compressionModel);
        }

        public void Deserialize(ref DataStreamReader reader, ref PlayerCommand data, in PlayerCommand baseline, NetworkCompressionModel compressionModel)
        {
            data.Keys = (byte) reader.ReadPackedUIntDelta(baseline.Keys, compressionModel);
        }
    }
    public class PlayerCommandSendCommandSystem : CommandSendSystem<PlayerCommandSerializer, PlayerCommand>
    {
        [BurstCompile]
        struct SendJob : IJobEntityBatch
        {
            public SendJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendJob{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
    public class PlayerCommandReceiveCommandSystem : CommandReceiveSystem<PlayerCommandSerializer, PlayerCommand>
    {
        [BurstCompile]
        struct ReceiveJob : IJobEntityBatch
        {
            public ReceiveJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var recvJob = new ReceiveJob{data = InitJobData()};
            ScheduleJobData(recvJob);
        }
    }
}
