//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct RpcJoinGameAckSerializer : IComponentData, IRpcCommandSerializer<RpcJoinGameAck>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in RpcJoinGameAck data)
        {
            writer.WriteUInt(data.GhostsSubSceneGUID.Value.x);
            writer.WriteUInt(data.GhostsSubSceneGUID.Value.y);
            writer.WriteUInt(data.GhostsSubSceneGUID.Value.z);
            writer.WriteUInt(data.GhostsSubSceneGUID.Value.w);
            writer.WriteUInt(data.BoardSubSceneGUID.Value.x);
            writer.WriteUInt(data.BoardSubSceneGUID.Value.y);
            writer.WriteUInt(data.BoardSubSceneGUID.Value.z);
            writer.WriteUInt(data.BoardSubSceneGUID.Value.w);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state,  ref RpcJoinGameAck data)
        {
            data.GhostsSubSceneGUID.Value.x = (uint) reader.ReadUInt();
            data.GhostsSubSceneGUID.Value.y = (uint) reader.ReadUInt();
            data.GhostsSubSceneGUID.Value.z = (uint) reader.ReadUInt();
            data.GhostsSubSceneGUID.Value.w = (uint) reader.ReadUInt();
            data.BoardSubSceneGUID.Value.x = (uint) reader.ReadUInt();
            data.BoardSubSceneGUID.Value.y = (uint) reader.ReadUInt();
            data.BoardSubSceneGUID.Value.z = (uint) reader.ReadUInt();
            data.BoardSubSceneGUID.Value.w = (uint) reader.ReadUInt();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<RpcJoinGameAckSerializer, RpcJoinGameAck>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class RpcJoinGameAckRpcCommandRequestSystem : RpcCommandRequestSystem<RpcJoinGameAckSerializer, RpcJoinGameAck>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
